import Item from "./Item.js";
import Recipe from "./Recipe.js";
import * as Workstations from "./Workstations.js";

export const AMETHYST_PENDANT = new Item("Amethyst Pendant");
export const ANIMAL_HIDE = new Item("Animal Hide", Item.LOOTED);
export const BANSHEE = new Item("Banshee");
export const BLOOD_ESSENCE = new Item("Blood Essence", Item.FARMED | Item.LOOTED);
export const BLOOD_KEY = new Item("Blood Key");
export const BLOOD_ROSE = new Item("Blood Rose", Item.FARMED | Item.LOOTED);
export const BLOOD_ROSE_BREW = new Item("Blood Rose Brew");
export const BLOOD_ROSE_POTION = new Item("Blood Rose Potion");
export const BLOOD_ROSE_RING = new Item("Blood Rose Ring");
export const BLOOD_SNAPPER = new Item("Blood Snapper", Item.FARMED | Item.LOOTED);
export const BLOODMOON_BOOTS = new Item("Bloodmoon Boots");
export const BLOODMOON_CHESTGUARD = new Item("Bloodmoon Chestguard");
export const BLOODMOON_GLOVES = new Item("Bloodmoon Gloves");
export const BLOODMOON_LEGGINGS = new Item("Bloodmoon Leggings");
export const BONE = new Item("Bone", Item.LOOTED);
export const BONE_AXES = new Item("Bone Axes");
export const BONE_CASTLE_KEY = new Item("Bone Castle Key");
export const BONE_MACE = new Item("Bone Mace");
export const BONE_RING = new Item("Bone Ring");
export const BONE_SPEAR = new Item("Bone Spear");
export const BONE_SWORD = new Item("Bone Sword");
export const BONEGUARD_BOOTS = new Item("Boneguard Boots");
export const BONEGUARD_CHESTGUARD = new Item("Boneguard Chestguard");
export const BONEGUARD_GLOVES = new Item("Boneguard Gloves");
export const BONEGUARD_LEGGINGS = new Item("Boneguard Leggings");
export const BREW_OF_FEROCITY = new Item("Brew of Ferocity", Item.CRAFTED | Item.LOOTED);
export const CARPET_ROLL = new Item("Carpet Roll");
export const CLAY = new Item("Clay", Item.FARMED | Item.LOOTED);
export const CLAY_MOLD = new Item("Clay Mold", Item.CRAFTED | Item.LOOTED);
export const CLOTH = new Item("Cloth", Item.CRAFTED | Item.LOOTED);
export const COARSE_THREAD = new Item("Coarse Thread", Item.LOOTED);
export const COPPER_AXES = new Item("Copper Axes");
export const COPPER_CASTLE_KEY = new Item("Copper Castle Key");
export const COPPER_INGOT = new Item("Copper Ingot");
export const COPPER_MACE = new Item("Copper Mace");
export const COPPER_ORE = new Item("Copper Ore");
export const COPPER_SPEAR = new Item("Copper Spear");
export const COPPER_SWORD = new Item("Copper Sword");
export const CORRUPTED_ARTEFACT = new Item("Corrupted Artefact");
export const COTTON = new Item("Cotton", Item.FARMED | Item.LOOTED);
export const COTTON_YARN = new Item("Cotton Yarn", Item.CRAFTED | Item.LOOTED);
export const CRUDE_AMETHYST = new Item("Crude Amethyst", Item.FARMED | Item.LOOTED);
export const CRUDE_EMERALD = new Item("Crude Emerald", Item.FARMED | Item.LOOTED);
export const CRUDE_MISTSTONE = new Item("Crude Miststone", Item.FARMED | Item.LOOTED);
export const CRUDE_RUBY = new Item("Crude Ruby", Item.FARMED | Item.LOOTED);
export const CRUDE_SAPPHIRE = new Item("Crude Sapphire", Item.FARMED | Item.LOOTED);
export const CRUDE_TOPAZ = new Item("Crude Topaz", Item.FARMED | Item.LOOTED);
export const DARK_SILVER_AXES = new Item("Dark Silver Axes");
export const DARK_SILVER_CROSSBOW = new Item("Dark Silver Crossbow");
export const DARK_SILVER_INGOT = new Item("Dark Silver Ingot");
export const DARK_SILVER_MACE = new Item("Dark Silver Mace");
export const DARK_SILVER_REAPER = new Item("Dark Silver Reaper");
export const DARK_SILVER_SLASHERS = new Item("Dark Silver Slashers");
export const DARK_SILVER_SPEAR = new Item("Dark Silver Spear");
export const DARK_SILVER_SWORD = new Item("Dark Silver Sword");
export const DAWNTHORN_BOOTS = new Item("Dawnthorn Boots");
export const DAWNTHORN_CHESTGUARD = new Item("Dawnthorn Chestguard");
export const DAWNTHORN_GLOVES = new Item("Dawnthorn Gloves");
export const DAWNTHORN_LEGGINGS = new Item("Dawnthorn Leggings");
export const DUSKWATCHERS_RING = new Item("Duskwatcher's Ring");
export const EMERALD_NECKLACE = new Item("Emerald Necklace");
export const EMPTY_CANTEEN = new Item("Empty Canteen", Item.CRAFTED | Item.LOOTED);
export const EMPTY_GLASS_BOTTLE = new Item("Empty Glass Bottle", Item.CRAFTED | Item.LOOTED);
export const ENCHANTED_BREW = new Item("Enchanted Brew", Item.CRAFTED | Item.LOOTED);
export const EXQUISITE_HEART = new Item("Exquisite Heart", Item.FARMED | Item.LOOTED);
export const FIERCE_STINGER = new Item("Fierce Stinger", Item.FARMED | Item.LOOTED);
export const FIRE_BLOSSOM = new Item("Fire Blossom");
export const FIRE_RESISTANCE_BREW = new Item("Fire Resistance Brew", Item.CRAFTED | Item.LOOTED);
export const FISH_BONE = new Item("Fish Bone", Item.FARMED | Item.LOOTED);
export const FISH_OIL = new Item("Fish Oil", Item.FARMED | Item.LOOTED);
export const FISHING_POLE = new Item("Fishing Pole");
export const FLAWLESS_AMETHYST = new Item("Flawless Amethyst", Item.CRAFTED | Item.LOOTED);
export const FLAWLESS_EMERALD = new Item("Flawless Emerald", Item.CRAFTED | Item.LOOTED);
export const FLAWLESS_MISTSTONE = new Item("Flawless Miststone", Item.CRAFTED | Item.LOOTED);
export const FLAWLESS_RUBY = new Item("Flawless Ruby", Item.CRAFTED | Item.LOOTED);
export const FLAWLESS_SAPPHIRE = new Item("Flawless Sapphire", Item.CRAFTED | Item.LOOTED);
export const FLAWLESS_TOPAZ = new Item("Flawless Topaz", Item.CRAFTED | Item.LOOTED);
export const GARLIC_RESISTANCE_POTION = new Item("Garlic Resistance Potion", Item.CRAFTED | Item.LOOTED);
export const GEM_DUST = new Item("Gem Dust", Item.FARMED | Item.LOOTED);
export const GHOST_CRYSTAL = new Item("Ghost Crystal", Item.FARMED | Item.LOOTED);
export const GHOST_SHROOM = new Item("Ghost Shroom", Item.FARMED | Item.LOOTED);
export const GHOST_YARN = new Item("Ghost Yarn", Item.CRAFTED | Item.LOOTED);
export const GHOUL = new Item("Ghoul");
export const GIANT_RAT = new Item("Giant Rat");
export const GLASS = new Item("Glass", Item.CRAFTED | Item.LOOTED);
export const GOLD_INGOT = new Item("Gold Ingot");
export const GOLDEN_CASTLE_KEY = new Item("Golden Castle Key");
export const GOLDEN_JEWELRY = new Item("Golden Jewelry", Item.LOOTED);
export const GOLDEN_RIVER_BASS = new Item("Golden River Bass", Item.FARMED | Item.LOOTED);
export const GRAVE_DUST = new Item("Grave Dust", Item.CRAFTED | Item.LOOTED);
export const GRAVEDIGGER_RING = new Item("Gravedigger Ring");
export const GREATER_BLOOD_ESSENCE = new Item("Greater Blood Essence");
export const HELLS_CLARION = new Item("Hells Clarion", Item.FARMED | Item.LOOTED);
export const HIGHLAND_LOTUS = new Item("Highland Lotus", Item.FARMED | Item.LOOTED);
export const HOLLOWFANG_BOOTS = new Item("Hollowfang Boots");
export const HOLLOWFANG_CHESTGUARD = new Item("Hollowfang Chestguard");
export const HOLLOWFANG_GLOVES = new Item("Hollowfang Gloves");
export const HOLLOWFANG_LEGGINGS = new Item("Hollowfang Leggings");
export const HOLY_RESISTANCE_FLASK = new Item("Holy Resistance Flask");
export const HOLY_RESISTANCE_POTION = new Item("Holy Resistance Potion");
export const HUNTERS_CLOAK = new Item("Hunter's Cloak");
export const HUNTERS_CROSSBOW = new Item("Hunter's Crossbow");
export const IMMORTAL_KINGS_CLOAK = new Item("Immortal King's Cloak");
export const IMMORTAL_KINGS_DRAPE = new Item("Immortal King's Drape");
export const IMMORTAL_KINGS_GREATHELM = new Item("Immortal King's Greathelm");
export const IMMORTAL_KINGS_MANTLE = new Item("Immortal King's Mantle");
export const IMPERIAL_THREAD = new Item("Imperial Thread", Item.CRAFTED | Item.LOOTED);
export const IRON_AXES = new Item("Iron Axes");
export const IRON_BODY = new Item("Iron Body");
export const IRON_CASTLE_KEY = new Item("Iron Castle Key");
export const IRON_CROSSBOW = new Item("Iron Crossbow");
export const IRON_INGOT = new Item("Iron Ingot", Item.CRAFTED | Item.LOOTED);
export const IRON_MACE = new Item("Iron Mace");
export const IRON_ORE = new Item("Iron Ore", Item.FARMED | Item.LOOTED);
export const IRON_REAPER = new Item("Iron Reaper");
export const IRON_SLASHERS = new Item("Iron Slashers");
export const IRON_SPEAR = new Item("Iron Spear");
export const IRON_SWORD = new Item("Iron Sword");
export const JEWEL_OF_THE_WICKED_PROPHET = new Item("Jewel of the Wicked Prophet");
export const LEATHER = new Item("Leather", Item.CRAFTED | Item.LOOTED);
export const LUMBER = new Item("Lumber", Item.FARMED | Item.LOOTED);
export const MAJOR_EXPLOSIVE_BOX = new Item("Major Explosive Box");
export const MERCILESS_COPPER_AXES = new Item("Merciless Copper Axes");
export const MERCILESS_COPPER_MACE = new Item("Merciless Copper Mace");
export const MERCILESS_COPPER_SPEAR = new Item("Merciless Copper Spear");
export const MERCILESS_COPPER_SWORD = new Item("Merciless Copper Sword");
export const MERCILESS_HOLLOWFANG_BOOTS = new Item("Merciless Hollowfang Boots");
export const MERCILESS_HOLLOWFANG_CHESTGUARD = new Item("Merciless Hollowfang Chestguard");
export const MERCILESS_HOLLOWFANG_GLOVES = new Item("Merciless Hollowfang Gloves");
export const MERCILESS_HOLLOWFANG_LEGGINGS = new Item("Merciless Hollowfang Leggings");
export const MERCILESS_HUNTERS_CROSSBOW = new Item("Merciless Hunter's Crossbow");
export const MERCILESS_IRON_AXES = new Item("Merciless Iron Axes");
export const MERCILESS_IRON_CROSSBOW = new Item("Merciless Iron Crossbow");
export const MERCILESS_IRON_MACE = new Item("Merciless Iron Mace");
export const MERCILESS_IRON_REAPER = new Item("Merciless Iron Reaper");
export const MERCILESS_IRON_SLASHERS = new Item("Merciless Iron Slashers");
export const MERCILESS_IRON_SPEAR = new Item("Merciless Iron Spear");
export const MERCILESS_IRON_SWORD = new Item("Merciless Iron Sword");
export const MERCILESS_NIGHSTALKER_BOOTS = new Item("Merciless Nightstalker Boots");
export const MERCILESS_NIGHSTALKER_GLOVES = new Item("Merciless Nightstalker Gloves");
export const MERCILESS_NIGHSTALKER_LEGGINGS = new Item("Merciless Nightstalker Leggings");
export const MERCILESS_NIGHSTALKER_VEST = new Item("Merciless Nightstalker Vest");
export const MINOR_EXPLOSIVE_BOX = new Item("Minor Explosive Box");
export const MINOR_GARLIC_RESISTANCE_BREW = new Item("Minor Garlic Resistance Brew", Item.CRAFTED | Item.LOOTED);
export const MINOR_SUN_RESISTANCE_BREW = new Item("Minor Sun Resistance Brew", Item.CRAFTED | Item.LOOTED);
export const MIST_SIGNET = new Item("Mist Signet");
export const MISTY_NECKLACE = new Item("Misty Necklace");
export const MOSQUITO = new Item("Mosquito");
export const MOURNING_LILY = new Item("Mourning Lily", Item.FARMED | Item.LOOTED);
export const NIGHSTALKER_BOOTS = new Item("Nightstalker Boots");
export const NIGHSTALKER_GLOVES = new Item("Nightstalker Gloves");
export const NIGHSTALKER_LEGGINGS = new Item("Nightstalker Leggings");
export const NIGHSTALKER_VEST = new Item("Nightstalker Vest");
export const NIGHTSTONE_OF_THE_BEAST = new Item("Nightstone of the Beast");
export const PAINTING_FRAME = new Item("Painting Frame");
export const PAPER = new Item("Paper", Item.CRAFTED | Item.LOOTED);
export const PHANTOMS_VEIL = new Item("Phantom's Veil");
export const PLANK = new Item("Plank", Item.CRAFTED | Item.LOOTED);
export const PLANT_FIBER = new Item("Plant Fiber", Item.FARMED | Item.LOOTED);
export const PLATED_BONEGUARD_BOOTS = new Item("Plated Boneguard Boots");
export const PLATED_BONEGUARD_CHESTGUARD = new Item("Plated Boneguard Chestguard");
export const PLATED_BONEGUARD_GLOVES = new Item("Plated Boneguard Gloves");
export const PLATED_BONEGUARD_LEGGINGS = new Item("Plated Boneguard Leggings");
export const POTION_OF_RAGE = new Item("Potion of Rage");
export const PRIMAL_BLOOD_ESSENCE = new Item("Primal Blood Essence");
export const PRISTINE_HIDE = new Item("Pristine Hide", Item.CRAFTED | Item.LOOTED);
export const PRISTINE_LEATHER = new Item("Pristine Leather", Item.CRAFTED | Item.LOOTED);
export const PUTRID_RAT = new Item("Putrid Rat");
export const QUARTZ = new Item("Quartz", Item.FARMED | Item.LOOTED);
export const RAT = new Item("Rat", Item.CRAFTED | Item.FARMED | Item.LOOTED);
export const REGULAR_AMETHYST = new Item("Regular Amethyst", Item.CRAFTED | Item.FARMED | Item.LOOTED);
export const REGULAR_EMERALD = new Item("Regular Emerald", Item.CRAFTED | Item.FARMED | Item.LOOTED);
export const REGULAR_MISTSTONE = new Item("Regular Miststone", Item.CRAFTED | Item.FARMED | Item.LOOTED);
export const REGULAR_RUBY = new Item("Regular Ruby", Item.CRAFTED | Item.FARMED | Item.LOOTED);
export const REGULAR_SAPPHIRE = new Item("Regular Sapphire", Item.CRAFTED | Item.FARMED | Item.LOOTED);
export const REGULAR_TOPAZ = new Item("Regular Topaz", Item.CRAFTED | Item.FARMED | Item.LOOTED);
export const REINFORCED_BONE_AXES = new Item("Reinforced Bone Axes");
export const REINFORCED_BONE_MACE = new Item("Reinforced Bone Mace");
export const REINFORCED_BONE_SPEAR = new Item("Reinforced Bone Spear");
export const REINFORCED_BONE_SWORD = new Item("Reinforced Bone Sword");
export const REINFORCED_PLANK = new Item("Reinforced Plank", Item.CRAFTED | Item.LOOTED);
export const RUBY_PENDANT = new Item("Ruby Pendant");
export const SANGUINE_AXES = new Item("Sanguine Axes");
export const SANGUINE_CROSSBOW = new Item("Sanguine Crossbow");
export const SANGUINE_MACE = new Item("Sanguine Mace");
export const SANGUINE_REAPER = new Item("Sanguine Reaper");
export const SANGUINE_SLASHERS = new Item("Sanguine Slashers");
export const SANGUINE_SPEAR = new Item("Sanguine Spear");
export const SANGUINE_SWORD = new Item("Sanguine Sword");
export const SAPPHIRE_PENDANT = new Item("Sapphire Pendant");
export const SAWDUST = new Item("Sawdust", Item.CRAFTED | Item.LOOTED);
export const SCALES = new Item("Scales", Item.LOOTED);
export const SCHEMATIC = new Item("Schematic", Item.CRAFTED | Item.LOOTED);
export const SCOURGE_PENDANT = new Item("Scourge Pendant");
export const SCOURGESTONE = new Item("Scourgestone", Item.CRAFTED | Item.LOOTED);
export const SCROLL = new Item("Scroll", Item.CRAFTED | Item.LOOTED);
export const SCULPTURED_WOOD = new Item("Sculptured Wood", Item.CRAFTED | Item.LOOTED);
export const SHARD_OF_THE_FROZEN_CRYPT = new Item("Shard of the Frozen Crypt");
export const SIEGE_GOLEM_STONE = new Item("Siege Golem Stone");
export const SILK = new Item("Silk", Item.CRAFTED | Item.LOOTED);
export const SILKWORM = new Item("Silkworm", Item.FARMED | Item.LOOTED);
export const SILVER_ORE = new Item("Silver Ore", Item.FARMED | Item.LOOTED);
export const SILVER_RESISTANCE_BREW = new Item("Silver Resistance Brew", Item.CRAFTED | Item.LOOTED);
export const SILVER_RESISTANCE_POTION = new Item("Silver Resistance Potion");
export const SKELETON = new Item("Skeleton");
export const SKELETON_PRIEST = new Item("Skeleton Priest");
export const SNOW_FLOWER = new Item("Snow Flower", Item.FARMED | Item.LOOTED);
export const SPECTRAL_DUST = new Item("Spectral Dust", Item.CRAFTED | Item.LOOTED);
export const SPIDERLING = new Item("Spiderling");
export const STONE = new Item("Stone", Item.FARMED | Item.LOOTED);
export const STONE_BODY = new Item("Stone Body", Item.CRAFTED | Item.LOOTED);
export const STONE_BRICK = new Item("Stone Brick", Item.CRAFTED | Item.LOOTED);
export const STONE_DUST = new Item("Stone Dust", Item.CRAFTED | Item.LOOTED);
export const SULPHUR = new Item("Sulphur", Item.CRAFTED | Item.LOOTED);
export const SULPHUR_ORE = new Item("Sulphur Ore", Item.FARMED | Item.LOOTED);
export const SUNFLOWER = new Item("Sunflower", Item.FARMED | Item.LOOTED);
export const SWAMP_DWELLER = new Item("Swamp Dweller", Item.FARMED | Item.LOOTED);
export const TAINTED_HEART = new Item("Tainted Heart", Item.FARMED | Item.LOOTED);
export const THE_EMBER_CHAIN = new Item("The Ember Chain");
export const THE_FROZEN_EYE = new Item("The Frozen Eye");
export const TOPAZ_AMULET = new Item("Topaz Amulet");
export const TRAVELERS_WRAP = new Item("Traveler's Wrap");
export const TWILIGHT_SNAPPER = new Item("Twilight Snapper", Item.FARMED | Item.LOOTED);
export const UNSULLIED_HEART = new Item("Unsullied Heart", Item.FARMED | Item.LOOTED);
export const VERMIN_SALVE = new Item("Vermin Salve", Item.CRAFTED | Item.LOOTED);
export const WATER_FILLED_BOTTLE = new Item("Water Filled Bottle");
export const WATER_FILLED_CANTEEN = new Item("Water Filled Canteen");
export const WHETSTONE = new Item("Whetstone", Item.CRAFTED | Item.LOOTED);
export const WITCH_POTION = new Item("Witch Potion");
export const WOOL_THREAD = new Item("Wool Thread", Item.CRAFTED | Item.LOOTED);
export const WRANGLERS_POTION = new Item("Wrangler's Potion");

AMETHYST_PENDANT.addRecipe(new Recipe(Workstations.JEWELCRAFTING_TABLE).addComponent(REGULAR_AMETHYST, 4).addComponent(SCOURGESTONE, 8).addComponent(SCOURGE_PENDANT).setRecipeTime(5));
BANSHEE.addRecipe(new Recipe(Workstations.TOMB).addComponent(GEM_DUST, 8).addComponent(HIGHLAND_LOTUS, 12).setRecipeTime(900));
BLOOD_ESSENCE.addRecipe(new Recipe(Workstations.BLOOD_PRESS).addComponent(RAT, 4).setRecipeTime(30).setRecipeYield(10));
BLOOD_ESSENCE.addRecipe(new Recipe(Workstations.BLOOD_PRESS).addComponent(TAINTED_HEART, 4).setRecipeTime(60).setRecipeYield(60));
BLOOD_KEY.addRecipe(new Recipe(Workstations.JEWELCRAFTING_TABLE).addComponent(GEM_DUST, 400).addComponent(DARK_SILVER_INGOT, 28).addComponent(GOLD_INGOT, 8).addComponent(PRIMAL_BLOOD_ESSENCE, 4).setRecipeTime(900));
BLOOD_ROSE_BREW.addRecipe(new Recipe(Workstations.ALCHEMY_TABLE).addComponent(BLOOD_ROSE, 40).addComponent(WATER_FILLED_CANTEEN).setRecipeTime(10));
BLOOD_ROSE_POTION.addRecipe(new Recipe(Workstations.ALCHEMY_TABLE).addComponent(BLOOD_ROSE, 80).addComponent(WATER_FILLED_BOTTLE).setRecipeTime(30));
BLOOD_ROSE_RING.addRecipe(new Recipe(Workstations.JEWELCRAFTING_TABLE).addComponent(PLANT_FIBER, 80).addComponent(BLOOD_ROSE, 30).addComponent(BONE_RING).setRecipeTime(5));
BLOODMOON_BOOTS.addRecipe(new Recipe(Workstations.TAILORING_BENCH).addComponent(DAWNTHORN_BOOTS).addComponent(IMPERIAL_THREAD, 12).addComponent(SILK, 8).addComponent(PRIMAL_BLOOD_ESSENCE).setRecipeTime(180));
BLOODMOON_CHESTGUARD.addRecipe(new Recipe(Workstations.TAILORING_BENCH).addComponent(DAWNTHORN_CHESTGUARD).addComponent(IMPERIAL_THREAD, 12).addComponent(SILK, 8).addComponent(PRIMAL_BLOOD_ESSENCE).setRecipeTime(180));
BLOODMOON_GLOVES.addRecipe(new Recipe(Workstations.TAILORING_BENCH).addComponent(DAWNTHORN_GLOVES).addComponent(IMPERIAL_THREAD, 12).addComponent(SILK, 8).addComponent(PRIMAL_BLOOD_ESSENCE).setRecipeTime(180));
BLOODMOON_LEGGINGS.addRecipe(new Recipe(Workstations.TAILORING_BENCH).addComponent(DAWNTHORN_LEGGINGS).addComponent(IMPERIAL_THREAD, 12).addComponent(SILK, 8).addComponent(PRIMAL_BLOOD_ESSENCE).setRecipeTime(180));
BONE_AXES.addRecipe(new Recipe(Workstations.INVENTORY).addComponent(BONE, 30).setRecipeTime(10));
BONE_CASTLE_KEY.addRecipe(new Recipe(Workstations.SIMPLE_WORKBENCH).addComponent(BLOOD_ESSENCE, 320).addComponent(STONE, 1200).addComponent(ANIMAL_HIDE, 400).addComponent(BONE, 400).addComponent(PLANK, 40).setRecipeTime(60));
BONE_MACE.addRecipe(new Recipe(Workstations.INVENTORY).addComponent(BONE, 30).setRecipeTime(10));
BONE_RING.addRecipe(new Recipe(Workstations.JEWELCRAFTING_TABLE).addComponent(BONE, 40).setRecipeTime(10));
BONE_SPEAR.addRecipe(new Recipe(Workstations.INVENTORY).addComponent(BONE, 30).setRecipeTime(10));
BONE_SWORD.addRecipe(new Recipe(Workstations.INVENTORY).addComponent(BONE, 30).setRecipeTime(10));
BONEGUARD_BOOTS.addRecipe(new Recipe(Workstations.INVENTORY).addComponent(BONE, 20).addComponent(ANIMAL_HIDE, 30).setRecipeTime(10));
BONEGUARD_CHESTGUARD.addRecipe(new Recipe(Workstations.INVENTORY).addComponent(BONE, 30).setRecipeTime(10));
BONEGUARD_GLOVES.addRecipe(new Recipe(Workstations.INVENTORY).addComponent(BONE, 20).addComponent(ANIMAL_HIDE, 30).setRecipeTime(10));
BONEGUARD_LEGGINGS.addRecipe(new Recipe(Workstations.INVENTORY).addComponent(BONE, 30).setRecipeTime(10));
BREW_OF_FEROCITY.addRecipe(new Recipe(Workstations.ALCHEMY_TABLE).addComponent(HELLS_CLARION, 30).addComponent(FISH_BONE).addComponent(WATER_FILLED_CANTEEN).setRecipeTime(30));
CARPET_ROLL.addRecipe(new Recipe(Workstations.TAILORING_BENCH).addComponent(CLOTH, 4).setRecipeTime(30));
CLAY_MOLD.addRecipe(new Recipe(Workstations.GRINDER).addComponent(CLAY, 12).addComponent(WATER_FILLED_CANTEEN).setRecipeTime(30));
CLOTH.addRecipe(new Recipe(Workstations.LOOM).addComponent(LEATHER, 4).addComponent(PLANT_FIBER, 12).setRecipeTime(30));
COPPER_AXES.addRecipe(new Recipe(Workstations.SIMPLE_WORKBENCH).addComponent(COPPER_INGOT, 16).addComponent(PLANK, 12).setRecipeTime(30));
COPPER_CASTLE_KEY.addRecipe(new Recipe(Workstations.SIMPLE_WORKBENCH).addComponent(GREATER_BLOOD_ESSENCE, 4).addComponent(STONE_BRICK, 240).addComponent(PLANK, 80).addComponent(COPPER_INGOT, 80).addComponent(LEATHER, 60).setRecipeTime(90));
COPPER_INGOT.addRecipe(new Recipe(Workstations.FURNACE).addComponent(COPPER_ORE, 20).setRecipeTime(30));
COPPER_MACE.addRecipe(new Recipe(Workstations.SIMPLE_WORKBENCH).addComponent(COPPER_INGOT, 16).addComponent(PLANK, 12).setRecipeTime(30));
COPPER_SPEAR.addRecipe(new Recipe(Workstations.SIMPLE_WORKBENCH).addComponent(COPPER_INGOT, 16).addComponent(PLANK, 12).setRecipeTime(30));
COPPER_SWORD.addRecipe(new Recipe(Workstations.SIMPLE_WORKBENCH).addComponent(COPPER_INGOT, 16).addComponent(PLANK, 12).setRecipeTime(30));
CORRUPTED_ARTEFACT.addRecipe(new Recipe(Workstations.JEWELCRAFTING_TABLE).addComponent(GOLDEN_JEWELRY, 8).addComponent(SPECTRAL_DUST, 8).setRecipeTime(90));
COTTON_YARN.addRecipe(new Recipe(Workstations.LOOM).addComponent(COTTON, 20).setRecipeTime(90));
DARK_SILVER_AXES.addRecipe(new Recipe(Workstations.ANVIL).addComponent(DARK_SILVER_INGOT, 16).addComponent(REINFORCED_PLANK, 8).setRecipeTime(180));
DARK_SILVER_CROSSBOW.addRecipe(new Recipe(Workstations.WOODWORKING_BENCH).addComponent(DARK_SILVER_INGOT, 20).addComponent(REINFORCED_PLANK, 8).setRecipeTime(180));
DARK_SILVER_INGOT.addRecipe(new Recipe(Workstations.FURNACE).addComponent(SCOURGESTONE).addComponent(SILVER_ORE, 20).setRecipeTime(180));
DARK_SILVER_MACE.addRecipe(new Recipe(Workstations.ANVIL).addComponent(DARK_SILVER_INGOT, 16).addComponent(REINFORCED_PLANK, 8).setRecipeTime(180));
DARK_SILVER_REAPER.addRecipe(new Recipe(Workstations.ANVIL).addComponent(DARK_SILVER_INGOT, 16).addComponent(REINFORCED_PLANK, 8).setRecipeTime(180));
DARK_SILVER_SLASHERS.addRecipe(new Recipe(Workstations.ANVIL).addComponent(DARK_SILVER_INGOT, 16).addComponent(REINFORCED_PLANK, 8).setRecipeTime(180));
DARK_SILVER_SPEAR.addRecipe(new Recipe(Workstations.ANVIL).addComponent(DARK_SILVER_INGOT, 16).addComponent(REINFORCED_PLANK, 8).setRecipeTime(180));
DARK_SILVER_SWORD.addRecipe(new Recipe(Workstations.ANVIL).addComponent(DARK_SILVER_INGOT, 16).addComponent(REINFORCED_PLANK, 8).setRecipeTime(180));
DAWNTHORN_BOOTS.addRecipe(new Recipe(Workstations.TAILORING_BENCH).addComponent(SCALES, 160).addComponent(PRISTINE_LEATHER, 12).addComponent(GHOST_YARN, 8).setRecipeTime(90));
DAWNTHORN_CHESTGUARD.addRecipe(new Recipe(Workstations.TAILORING_BENCH).addComponent(SCALES, 160).addComponent(PRISTINE_LEATHER, 12).addComponent(GHOST_YARN, 8).setRecipeTime(90));
DAWNTHORN_GLOVES.addRecipe(new Recipe(Workstations.TAILORING_BENCH).addComponent(SCALES, 160).addComponent(PRISTINE_LEATHER, 12).addComponent(GHOST_YARN, 8).setRecipeTime(90));
DAWNTHORN_LEGGINGS.addRecipe(new Recipe(Workstations.TAILORING_BENCH).addComponent(SCALES, 160).addComponent(PRISTINE_LEATHER, 12).addComponent(GHOST_YARN, 8).setRecipeTime(90));
DUSKWATCHERS_RING.addRecipe(new Recipe(Workstations.JEWELCRAFTING_TABLE).addComponent(GREATER_BLOOD_ESSENCE).addComponent(CRUDE_TOPAZ, 4).addComponent(GRAVE_DUST, 8).setRecipeTime(30));
EMERALD_NECKLACE.addRecipe(new Recipe(Workstations.JEWELCRAFTING_TABLE).addComponent(REGULAR_EMERALD, 4).addComponent(SCOURGESTONE, 8).addComponent(SCOURGE_PENDANT).setRecipeTime(5));
EMPTY_CANTEEN.addRecipe(new Recipe(Workstations.TANNERY).addComponent(LEATHER, 4).addComponent(PLANT_FIBER, 20).setRecipeTime(10));
EMPTY_GLASS_BOTTLE.addRecipe(new Recipe(Workstations.ALCHEMY_TABLE).addComponent(GLASS, 4).setRecipeTime(10));
ENCHANTED_BREW.addRecipe(new Recipe(Workstations.ALCHEMY_TABLE).addComponent(SNOW_FLOWER, 30).addComponent(FISH_BONE).addComponent(WATER_FILLED_CANTEEN).setRecipeTime(30));
FIRE_RESISTANCE_BREW.addRecipe(new Recipe(Workstations.ALCHEMY_TABLE).addComponent(FIRE_BLOSSOM, 40).addComponent(FISH_OIL, 4).addComponent(WATER_FILLED_CANTEEN).setRecipeTime(30));
FISHING_POLE.addRecipe(new Recipe(Workstations.WOODWORKING_BENCH).addComponent(PLANK, 8).addComponent(COPPER_INGOT, 4).addComponent(COARSE_THREAD, 4).setRecipeTime(60))
FLAWLESS_AMETHYST.addRecipe(new Recipe(Workstations.GEM_CUTTING_TABLE).addComponent(REGULAR_AMETHYST, 4).setRecipeTime(180)); // Tailoring Bench
FLAWLESS_EMERALD.addRecipe(new Recipe(Workstations.GEM_CUTTING_TABLE).addComponent(REGULAR_EMERALD, 4).setRecipeTime(180));
FLAWLESS_MISTSTONE.addRecipe(new Recipe(Workstations.GEM_CUTTING_TABLE).addComponent(REGULAR_MISTSTONE, 4).setRecipeTime(180));
FLAWLESS_RUBY.addRecipe(new Recipe(Workstations.GEM_CUTTING_TABLE).addComponent(REGULAR_RUBY, 4).setRecipeTime(180));
FLAWLESS_SAPPHIRE.addRecipe(new Recipe(Workstations.GEM_CUTTING_TABLE).addComponent(REGULAR_SAPPHIRE, 4).setRecipeTime(180));
FLAWLESS_TOPAZ.addRecipe(new Recipe(Workstations.GEM_CUTTING_TABLE).addComponent(REGULAR_TOPAZ, 4).setRecipeTime(180));
GARLIC_RESISTANCE_POTION.addRecipe(new Recipe(Workstations.ALCHEMY_TABLE).addComponent(HELLS_CLARION, 20).addComponent(SUNFLOWER, 20).addComponent(RAT, 4).addComponent(WATER_FILLED_BOTTLE).setRecipeTime(60));
GHOST_YARN.addRecipe(new Recipe(Workstations.LOOM).addComponent(GHOST_SHROOM, 8).addComponent(COTTON_YARN, 4).setRecipeTime(180));
GHOUL.addRecipe(new Recipe(Workstations.TOMB).addComponent(MOURNING_LILY, 12).setRecipeTime(300));
GIANT_RAT.addRecipe(new Recipe(Workstations.VERMIN_NEST).addComponent(PLANT_FIBER, 12).addComponent(FISH_BONE).setRecipeTime(30));
GLASS.addRecipe(new Recipe(Workstations.FURNACE).addComponent(QUARTZ, 20).setRecipeTime(60));
GOLD_INGOT.addRecipe(new Recipe(Workstations.FURNACE).addComponent(SULPHUR, 8).addComponent(GOLDEN_JEWELRY, 8).setRecipeTime(600));
GOLDEN_CASTLE_KEY.addRecipe(new Recipe(Workstations.ANVIL).addComponent(PRIMAL_BLOOD_ESSENCE, 12).addComponent(GOLD_INGOT, 24).addComponent(SPECTRAL_DUST, 40).addComponent(DARK_SILVER_INGOT, 80).addComponent(REINFORCED_PLANK, 80).setRecipeTime(900));
GRAVE_DUST.addRecipe(new Recipe(Workstations.GRINDER).addComponent(BONE, 100).setRecipeTime(60));
GRAVEDIGGER_RING.addRecipe(new Recipe(Workstations.JEWELCRAFTING_TABLE).addComponent(GRAVE_DUST, 8).addComponent(MOURNING_LILY, 40).setRecipeTime(20));
GREATER_BLOOD_ESSENCE.addRecipe(new Recipe(Workstations.BLOOD_PRESS).addComponent(BLOOD_ESSENCE, 250).setRecipeTime(180));
GREATER_BLOOD_ESSENCE.addRecipe(new Recipe(Workstations.BLOOD_PRESS).addComponent(UNSULLIED_HEART, 4).setRecipeTime(180));
HOLLOWFANG_BOOTS.addRecipe(new Recipe(Workstations.TAILORING_BENCH).addComponent(COTTON_YARN, 8).addComponent(LEATHER, 8).addComponent(WOOL_THREAD, 8).setRecipeTime(60));
HOLLOWFANG_CHESTGUARD.addRecipe(new Recipe(Workstations.TAILORING_BENCH).addComponent(COTTON_YARN, 8).addComponent(LEATHER, 8).addComponent(WOOL_THREAD, 8).setRecipeTime(60));
HOLLOWFANG_GLOVES.addRecipe(new Recipe(Workstations.TAILORING_BENCH).addComponent(COTTON_YARN, 8).addComponent(LEATHER, 8).addComponent(WOOL_THREAD, 8).setRecipeTime(60));
HOLLOWFANG_LEGGINGS.addRecipe(new Recipe(Workstations.TAILORING_BENCH).addComponent(COTTON_YARN, 8).addComponent(LEATHER, 8).addComponent(WOOL_THREAD, 8).setRecipeTime(60));
HOLY_RESISTANCE_FLASK.addRecipe(new Recipe(Workstations.ALCHEMY_TABLE).addComponent(SPECTRAL_DUST, 4).addComponent(HOLY_RESISTANCE_POTION).setRecipeTime(60));
HOLY_RESISTANCE_POTION.addRecipe(new Recipe(Workstations.ALCHEMY_TABLE).addComponent(MOURNING_LILY, 60).addComponent(SCOURGESTONE, 2).addComponent(WATER_FILLED_BOTTLE).setRecipeTime(60));
HUNTERS_CLOAK.addRecipe(new Recipe(Workstations.TAILORING_BENCH).addComponent(COTTON_YARN, 8).setRecipeTime(30));
HUNTERS_CROSSBOW.addRecipe(new Recipe(Workstations.WOODWORKING_BENCH).addComponent(PLANK, 12).addComponent(LEATHER, 6).setRecipeTime(30));
IMMORTAL_KINGS_CLOAK.addRecipe(new Recipe(Workstations.TAILORING_BENCH).addComponent(COTTON_YARN, 8).setRecipeTime(30));
IMMORTAL_KINGS_DRAPE.addRecipe(new Recipe(Workstations.TAILORING_BENCH).addComponent(CLOTH, 4).addComponent(LEATHER, 4).setRecipeTime(10));
IMMORTAL_KINGS_GREATHELM.addRecipe(new Recipe(Workstations.INVENTORY).addComponent(COPPER_INGOT, 4).addComponent(LEATHER, 4).setRecipeTime(10));
IMMORTAL_KINGS_MANTLE.addRecipe(new Recipe(Workstations.TAILORING_BENCH).addComponent(GHOST_YARN, 8).addComponent(SPECTRAL_DUST, 8).setRecipeTime(60));
IMPERIAL_THREAD.addRecipe(new Recipe(Workstations.LOOM).addComponent(WOOL_THREAD, 8).addComponent(SUNFLOWER, 12).addComponent(SNOW_FLOWER, 12).setRecipeTime(60));
IRON_AXES.addRecipe(new Recipe(Workstations.SMITHY).addComponent(IRON_INGOT, 20).addComponent(PLANK, 16).setRecipeTime(60));
IRON_BODY.addRecipe(new Recipe(Workstations.SMITHY).addComponent(IRON_INGOT, 4).setRecipeTime(30));
IRON_CASTLE_KEY.addRecipe(new Recipe(Workstations.SMITHY).addComponent(GREATER_BLOOD_ESSENCE, 20).addComponent(GEM_DUST, 240).addComponent(SCOURGESTONE, 80).addComponent(REINFORCED_PLANK, 60).setRecipeTime(300));
IRON_CROSSBOW.addRecipe(new Recipe(Workstations.WOODWORKING_BENCH).addComponent(IRON_INGOT, 20).addComponent(PLANK, 16).setRecipeTime(60));
IRON_INGOT.addRecipe(new Recipe(Workstations.FURNACE).addComponent(IRON_ORE, 20).setRecipeTime(180));
IRON_MACE.addRecipe(new Recipe(Workstations.SMITHY).addComponent(IRON_INGOT, 20).addComponent(PLANK, 16).setRecipeTime(60));
IRON_REAPER.addRecipe(new Recipe(Workstations.SMITHY).addComponent(IRON_INGOT, 20).addComponent(PLANK, 16).setRecipeTime(60));
IRON_SLASHERS.addRecipe(new Recipe(Workstations.SMITHY).addComponent(IRON_INGOT, 20).addComponent(PLANK, 16).setRecipeTime(60));
IRON_SPEAR.addRecipe(new Recipe(Workstations.SMITHY).addComponent(IRON_INGOT, 20).addComponent(PLANK, 16).setRecipeTime(60));
IRON_SWORD.addRecipe(new Recipe(Workstations.SMITHY).addComponent(IRON_INGOT, 20).addComponent(PLANK, 16).setRecipeTime(60));
JEWEL_OF_THE_WICKED_PROPHET.addRecipe(new Recipe(Workstations.JEWELCRAFTING_TABLE).addComponent(FLAWLESS_RUBY, 4).addComponent(GOLD_INGOT, 8).addComponent(CORRUPTED_ARTEFACT).setRecipeTime(180));
LEATHER.addRecipe(new Recipe(Workstations.TANNERY).addComponent(ANIMAL_HIDE, 16).setRecipeTime(30));
MAJOR_EXPLOSIVE_BOX.addRecipe(new Recipe(Workstations.ALCHEMY_TABLE).addComponent(SULPHUR, 12).addComponent(REINFORCED_PLANK, 8).addComponent(GEM_DUST, 40).setRecipeTime(90));
MERCILESS_COPPER_AXES.addRecipe(new Recipe(Workstations.SIMPLE_WORKBENCH).addComponent(COPPER_AXES).addComponent(CRUDE_RUBY, 2).addComponent(WHETSTONE, 8).addComponent(LEATHER, 4).setRecipeTime(5));
MERCILESS_COPPER_MACE.addRecipe(new Recipe(Workstations.SIMPLE_WORKBENCH).addComponent(COPPER_MACE).addComponent(CRUDE_TOPAZ, 2).addComponent(WHETSTONE, 8).addComponent(LEATHER, 4).setRecipeTime(5));
MERCILESS_COPPER_SPEAR.addRecipe(new Recipe(Workstations.SIMPLE_WORKBENCH).addComponent(COPPER_SPEAR).addComponent(CRUDE_EMERALD, 2).addComponent(WHETSTONE, 8).addComponent(LEATHER, 4).setRecipeTime(5));
MERCILESS_COPPER_SWORD.addRecipe(new Recipe(Workstations.SIMPLE_WORKBENCH).addComponent(COPPER_SWORD).addComponent(CRUDE_SAPPHIRE, 2).addComponent(WHETSTONE, 8).addComponent(LEATHER, 4).setRecipeTime(5));
MERCILESS_HOLLOWFANG_BOOTS.addRecipe(new Recipe(Workstations.TAILORING_BENCH).addComponent(HOLLOWFANG_BOOTS).addComponent(IRON_INGOT, 12).setRecipeTime(5));
MERCILESS_HOLLOWFANG_CHESTGUARD.addRecipe(new Recipe(Workstations.TAILORING_BENCH).addComponent(HOLLOWFANG_CHESTGUARD).addComponent(IRON_INGOT, 12).setRecipeTime(5));
MERCILESS_HOLLOWFANG_GLOVES.addRecipe(new Recipe(Workstations.TAILORING_BENCH).addComponent(HOLLOWFANG_GLOVES).addComponent(IRON_INGOT, 12).setRecipeTime(5));
MERCILESS_HOLLOWFANG_LEGGINGS.addRecipe(new Recipe(Workstations.TAILORING_BENCH).addComponent(HOLLOWFANG_LEGGINGS).addComponent(IRON_INGOT, 12).setRecipeTime(5));
MERCILESS_HUNTERS_CROSSBOW.addRecipe(new Recipe(Workstations.WOODWORKING_BENCH).addComponent(HUNTERS_CROSSBOW).addComponent(GEM_DUST, 2).addComponent(WHETSTONE, 8).addComponent(LEATHER, 4).setRecipeTime(5));
MERCILESS_IRON_AXES.addRecipe(new Recipe(Workstations.SMITHY).addComponent(IRON_AXES).addComponent(REGULAR_RUBY, 4).addComponent(GREATER_BLOOD_ESSENCE, 4).addComponent(REINFORCED_PLANK, 4).setRecipeTime(5));
MERCILESS_IRON_CROSSBOW.addRecipe(new Recipe(Workstations.WOODWORKING_BENCH).addComponent(IRON_CROSSBOW).addComponent(REINFORCED_PLANK, 8).addComponent(GREATER_BLOOD_ESSENCE, 4).setRecipeTime(5));
MERCILESS_IRON_MACE.addRecipe(new Recipe(Workstations.SMITHY).addComponent(IRON_MACE).addComponent(REGULAR_TOPAZ, 4).addComponent(GREATER_BLOOD_ESSENCE, 4).addComponent(REINFORCED_PLANK, 4).setRecipeTime(5));
MERCILESS_IRON_REAPER.addRecipe(new Recipe(Workstations.SMITHY).addComponent(IRON_REAPER).addComponent(REGULAR_MISTSTONE, 4).addComponent(GREATER_BLOOD_ESSENCE, 4).addComponent(REINFORCED_PLANK, 4).setRecipeTime(5));
MERCILESS_IRON_SLASHERS.addRecipe(new Recipe(Workstations.SMITHY).addComponent(IRON_SLASHERS).addComponent(REGULAR_AMETHYST, 4).addComponent(GREATER_BLOOD_ESSENCE, 4).addComponent(REINFORCED_PLANK, 4).setRecipeTime(5));
MERCILESS_IRON_SPEAR.addRecipe(new Recipe(Workstations.SMITHY).addComponent(IRON_SPEAR).addComponent(REGULAR_EMERALD, 4).addComponent(GREATER_BLOOD_ESSENCE, 4).addComponent(REINFORCED_PLANK, 4).setRecipeTime(5));
MERCILESS_IRON_SWORD.addRecipe(new Recipe(Workstations.SMITHY).addComponent(IRON_SWORD).addComponent(REGULAR_SAPPHIRE, 4).addComponent(GREATER_BLOOD_ESSENCE, 4).addComponent(REINFORCED_PLANK, 4).setRecipeTime(5));
MERCILESS_NIGHSTALKER_BOOTS.addRecipe(new Recipe(Workstations.SIMPLE_WORKBENCH).addComponent(NIGHSTALKER_BOOTS).addComponent(LEATHER, 4).addComponent(COARSE_THREAD, 4).addComponent(COPPER_INGOT, 8).setRecipeTime(5));
MERCILESS_NIGHSTALKER_GLOVES.addRecipe(new Recipe(Workstations.SIMPLE_WORKBENCH).addComponent(NIGHSTALKER_GLOVES).addComponent(LEATHER, 4).addComponent(COARSE_THREAD, 4).addComponent(COPPER_INGOT, 8).setRecipeTime(5));
MERCILESS_NIGHSTALKER_LEGGINGS.addRecipe(new Recipe(Workstations.SIMPLE_WORKBENCH).addComponent(NIGHSTALKER_LEGGINGS).addComponent(LEATHER, 4).addComponent(COARSE_THREAD, 4).addComponent(COPPER_INGOT, 8).setRecipeTime(5));
MERCILESS_NIGHSTALKER_VEST.addRecipe(new Recipe(Workstations.SIMPLE_WORKBENCH).addComponent(NIGHSTALKER_VEST).addComponent(LEATHER, 4).addComponent(COARSE_THREAD, 4).addComponent(COPPER_INGOT, 8).setRecipeTime(5));
MINOR_EXPLOSIVE_BOX.addRecipe(new Recipe(Workstations.ALCHEMY_TABLE).addComponent(SULPHUR, 8).addComponent(PLANK, 8).addComponent(WHETSTONE, 4).setRecipeTime(60));
MINOR_GARLIC_RESISTANCE_BREW.addRecipe(new Recipe(Workstations.ALCHEMY_TABLE).addComponent(HELLS_CLARION, 40).addComponent(RAT, 4).addComponent(WATER_FILLED_CANTEEN).setRecipeTime(30));
MINOR_SUN_RESISTANCE_BREW.addRecipe(new Recipe(Workstations.ALCHEMY_TABLE).addComponent(MOURNING_LILY, 20).addComponent(BLOOD_ROSE, 20).addComponent(WATER_FILLED_CANTEEN).setRecipeTime(30));
MIST_SIGNET.addRecipe(new Recipe(Workstations.JEWELCRAFTING_TABLE).addComponent(GREATER_BLOOD_ESSENCE).addComponent(CRUDE_MISTSTONE, 4).addComponent(GRAVE_DUST, 8).setRecipeTime(30));
MISTY_NECKLACE.addRecipe(new Recipe(Workstations.JEWELCRAFTING_TABLE).addComponent(REGULAR_MISTSTONE, 4).addComponent(SCOURGESTONE, 8).addComponent(SCOURGE_PENDANT).setRecipeTime(5));
MOSQUITO.addRecipe(new Recipe(Workstations.VERMIN_NEST).addComponent(HIGHLAND_LOTUS, 20).addComponent(BLOOD_SNAPPER).setRecipeTime(30).setRecipeYield(3));
NIGHSTALKER_BOOTS.addRecipe(new Recipe(Workstations.SIMPLE_WORKBENCH).addComponent(LEATHER, 6).addComponent(COARSE_THREAD, 4).setRecipeTime(20));
NIGHSTALKER_GLOVES.addRecipe(new Recipe(Workstations.SIMPLE_WORKBENCH).addComponent(LEATHER, 6).addComponent(COARSE_THREAD, 4).setRecipeTime(20));
NIGHSTALKER_LEGGINGS.addRecipe(new Recipe(Workstations.SIMPLE_WORKBENCH).addComponent(LEATHER, 6).addComponent(COARSE_THREAD, 4).setRecipeTime(20));
NIGHSTALKER_VEST.addRecipe(new Recipe(Workstations.SIMPLE_WORKBENCH).addComponent(LEATHER, 6).addComponent(COARSE_THREAD, 4).setRecipeTime(20));
NIGHTSTONE_OF_THE_BEAST.addRecipe(new Recipe(Workstations.JEWELCRAFTING_TABLE).addComponent(FLAWLESS_AMETHYST, 4).addComponent(GOLD_INGOT, 8).addComponent(CORRUPTED_ARTEFACT).setRecipeTime(180));
PAINTING_FRAME.addRecipe(new Recipe(Workstations.WOODWORKING_BENCH).addComponent(PLANK, 4).setRecipeTime(30));
PAPER.addRecipe(new Recipe(Workstations.PAPER_PRESS).addComponent(PLANT_FIBER, 4).addComponent(SAWDUST, 12).setRecipeTime(10));
PHANTOMS_VEIL.addRecipe(new Recipe(Workstations.TAILORING_BENCH).addComponent(GHOST_YARN, 8).addComponent(SPECTRAL_DUST, 8).setRecipeTime(60));
PLANK.addRecipe(new Recipe(Workstations.SAWMILL).addComponent(LUMBER, 20).setRecipeTime(20));
PLATED_BONEGUARD_BOOTS.addRecipe(new Recipe(Workstations.SIMPLE_WORKBENCH).addComponent(BONEGUARD_BOOTS).addComponent(ANIMAL_HIDE, 60).setRecipeTime(5));
PLATED_BONEGUARD_CHESTGUARD.addRecipe(new Recipe(Workstations.SIMPLE_WORKBENCH).addComponent(BONEGUARD_CHESTGUARD).addComponent(ANIMAL_HIDE, 60).setRecipeTime(5));
PLATED_BONEGUARD_GLOVES.addRecipe(new Recipe(Workstations.SIMPLE_WORKBENCH).addComponent(BONEGUARD_GLOVES).addComponent(ANIMAL_HIDE, 60).setRecipeTime(5));
PLATED_BONEGUARD_LEGGINGS.addRecipe(new Recipe(Workstations.SIMPLE_WORKBENCH).addComponent(BONEGUARD_LEGGINGS).addComponent(ANIMAL_HIDE, 60).setRecipeTime(5));
POTION_OF_RAGE.addRecipe(new Recipe(Workstations.ALCHEMY_TABLE).addComponent(FIERCE_STINGER).addComponent(HELLS_CLARION, 90).addComponent(WATER_FILLED_BOTTLE).setRecipeTime(30));
PRIMAL_BLOOD_ESSENCE.addRecipe(new Recipe(Workstations.BLOOD_PRESS).addComponent(EXQUISITE_HEART, 4).setRecipeTime(180));
PRIMAL_BLOOD_ESSENCE.addRecipe(new Recipe(Workstations.BLOOD_PRESS).addComponent(GREATER_BLOOD_ESSENCE, 12).setRecipeTime(180));
PRISTINE_LEATHER.addRecipe(new Recipe(Workstations.TANNERY).addComponent(FISH_OIL, 4).addComponent(PRISTINE_HIDE, 20).setRecipeTime(90));
PUTRID_RAT.addRecipe(new Recipe(Workstations.VERMIN_NEST).addComponent(TWILIGHT_SNAPPER).addComponent(FISH_BONE, 4).addComponent(GRAVE_DUST, 8).setRecipeTime(30));
RAT.addRecipe(new Recipe(Workstations.VERMIN_NEST).addComponent(PLANT_FIBER, 12).addComponent(BONE, 12).setRecipeTime(30));
REGULAR_AMETHYST.addRecipe(new Recipe(Workstations.GEM_CUTTING_TABLE).addComponent(CRUDE_AMETHYST, 4).setRecipeTime(180));
REGULAR_EMERALD.addRecipe(new Recipe(Workstations.GEM_CUTTING_TABLE).addComponent(CRUDE_EMERALD, 4).setRecipeTime(180));
REGULAR_MISTSTONE.addRecipe(new Recipe(Workstations.GEM_CUTTING_TABLE).addComponent(CRUDE_MISTSTONE, 4).setRecipeTime(180));
REGULAR_RUBY.addRecipe(new Recipe(Workstations.GEM_CUTTING_TABLE).addComponent(CRUDE_RUBY, 4).setRecipeTime(180));
REGULAR_SAPPHIRE.addRecipe(new Recipe(Workstations.GEM_CUTTING_TABLE).addComponent(CRUDE_SAPPHIRE, 4).setRecipeTime(180));
REGULAR_TOPAZ.addRecipe(new Recipe(Workstations.GEM_CUTTING_TABLE).addComponent(CRUDE_TOPAZ, 4).setRecipeTime(180));
REINFORCED_BONE_AXES.addRecipe(new Recipe(Workstations.SIMPLE_WORKBENCH).addComponent(BONE_AXES).addComponent(PLANK, 4).addComponent(STONE, 120).setRecipeTime(5));
REINFORCED_BONE_MACE.addRecipe(new Recipe(Workstations.SIMPLE_WORKBENCH).addComponent(BONE_MACE).addComponent(PLANK, 4).addComponent(STONE, 120).setRecipeTime(5));
REINFORCED_BONE_SPEAR.addRecipe(new Recipe(Workstations.SIMPLE_WORKBENCH).addComponent(BONE_SPEAR).addComponent(PLANK, 4).addComponent(STONE, 120).setRecipeTime(5));
REINFORCED_BONE_SWORD.addRecipe(new Recipe(Workstations.SIMPLE_WORKBENCH).addComponent(BONE_SWORD).addComponent(PLANK, 4).addComponent(STONE, 120).setRecipeTime(5));
REINFORCED_PLANK.addRecipe(new Recipe(Workstations.SAWMILL).addComponent(PLANK, 4).addComponent(IRON_INGOT, 4).setRecipeTime(60));
RUBY_PENDANT.addRecipe(new Recipe(Workstations.JEWELCRAFTING_TABLE).addComponent(REGULAR_RUBY, 4).addComponent(SCOURGESTONE, 8).addComponent(SCOURGE_PENDANT).setRecipeTime(5));
SANGUINE_AXES.addRecipe(new Recipe(Workstations.ANVIL).addComponent(DARK_SILVER_AXES).addComponent(FLAWLESS_RUBY, 4).addComponent(PRIMAL_BLOOD_ESSENCE, 4).addComponent(PRISTINE_LEATHER, 12).setRecipeTime(180));
SANGUINE_CROSSBOW.addRecipe(new Recipe(Workstations.WOODWORKING_BENCH).addComponent(DARK_SILVER_CROSSBOW).addComponent(IMPERIAL_THREAD, 16).addComponent(PRIMAL_BLOOD_ESSENCE, 4).addComponent(PRISTINE_LEATHER, 12).setRecipeTime(180));
SANGUINE_MACE.addRecipe(new Recipe(Workstations.ANVIL).addComponent(DARK_SILVER_MACE).addComponent(FLAWLESS_TOPAZ, 4).addComponent(PRIMAL_BLOOD_ESSENCE, 4).addComponent(PRISTINE_LEATHER, 12).setRecipeTime(180));
SANGUINE_REAPER.addRecipe(new Recipe(Workstations.ANVIL).addComponent(DARK_SILVER_REAPER).addComponent(FLAWLESS_MISTSTONE, 4).addComponent(PRIMAL_BLOOD_ESSENCE, 4).addComponent(PRISTINE_LEATHER, 12).setRecipeTime(180));
SANGUINE_SLASHERS.addRecipe(new Recipe(Workstations.ANVIL).addComponent(DARK_SILVER_SLASHERS).addComponent(FLAWLESS_AMETHYST, 4).addComponent(PRIMAL_BLOOD_ESSENCE, 4).addComponent(PRISTINE_LEATHER, 12).setRecipeTime(180));
SANGUINE_SPEAR.addRecipe(new Recipe(Workstations.ANVIL).addComponent(DARK_SILVER_SPEAR).addComponent(FLAWLESS_EMERALD, 4).addComponent(PRIMAL_BLOOD_ESSENCE, 4).addComponent(PRISTINE_LEATHER, 12).setRecipeTime(180));
SANGUINE_SWORD.addRecipe(new Recipe(Workstations.ANVIL).addComponent(DARK_SILVER_SWORD).addComponent(FLAWLESS_SAPPHIRE, 4).addComponent(PRIMAL_BLOOD_ESSENCE, 4).addComponent(PRISTINE_LEATHER, 12).setRecipeTime(180));
SAPPHIRE_PENDANT.addRecipe(new Recipe(Workstations.JEWELCRAFTING_TABLE).addComponent(REGULAR_SAPPHIRE, 4).addComponent(SCOURGESTONE, 8).addComponent(SCOURGE_PENDANT).setRecipeTime(5));
SAWDUST.addRecipe(new Recipe(Workstations.SAWMILL).addComponent(LUMBER, 20).setRecipeTime(20));
SCHEMATIC.addRecipe(new Recipe(Workstations.PAPER_PRESS).addComponent(SILVER_ORE, 24).addComponent(SPECTRAL_DUST, 4).addComponent(SCROLL, 8).setRecipeTime(20));
SCOURGE_PENDANT.addRecipe(new Recipe(Workstations.JEWELCRAFTING_TABLE).addComponent(SCOURGESTONE).addComponent(GLASS, 12).addComponent(SUNFLOWER, 60).setRecipeTime(60));
SCOURGESTONE.addRecipe(new Recipe(Workstations.FURNACE).addComponent(GLASS, 4).addComponent(GRAVE_DUST, 4).addComponent(WHETSTONE, 4).setRecipeTime(180));
SCROLL.addRecipe(new Recipe(Workstations.PAPER_PRESS).addComponent(GEM_DUST, 12).addComponent(PAPER, 4).setRecipeTime(20));
SCULPTURED_WOOD.addRecipe(new Recipe(Workstations.WOODWORKING_BENCH).addComponent(PLANK, 4).setRecipeTime(30));
SHARD_OF_THE_FROZEN_CRYPT.addRecipe(new Recipe(Workstations.JEWELCRAFTING_TABLE).addComponent(FLAWLESS_SAPPHIRE, 4).addComponent(GOLD_INGOT, 8).addComponent(CORRUPTED_ARTEFACT).setRecipeTime(180));
SIEGE_GOLEM_STONE.addRecipe(new Recipe(Workstations.GEM_CUTTING_TABLE).addComponent(STONE_BRICK, 200).addComponent(GEM_DUST, 200).addComponent(SCOURGESTONE, 16).addComponent(GREATER_BLOOD_ESSENCE, 12).setRecipeTime(3600));
SILK.addRecipe(new Recipe(Workstations.LOOM).addComponent(HIGHLAND_LOTUS, 8).addComponent(SILKWORM, 4).addComponent(CLOTH, 4).setRecipeTime(180));
SILVER_RESISTANCE_BREW.addRecipe(new Recipe(Workstations.ALCHEMY_TABLE).addComponent(SNOW_FLOWER, 20).addComponent(WATER_FILLED_CANTEEN).setRecipeTime(30));
SILVER_RESISTANCE_POTION.addRecipe(new Recipe(Workstations.ALCHEMY_TABLE).addComponent(GHOST_SHROOM, 32).addComponent(WATER_FILLED_BOTTLE).setRecipeTime(60));
SKELETON_PRIEST.addRecipe(new Recipe(Workstations.TOMB).addComponent(GEM_DUST, 4).addComponent(SUNFLOWER, 24).setRecipeTime(600));
SKELETON.addRecipe(new Recipe(Workstations.TOMB).addComponent(BLOOD_ROSE, 6).setRecipeTime(90));
SPECTRAL_DUST.addRecipe(new Recipe(Workstations.GRINDER).addComponent(GEM_DUST, 4).addComponent(GHOST_CRYSTAL, 40).setRecipeTime(60));
SPIDERLING.addRecipe(new Recipe(Workstations.VERMIN_NEST).addComponent(SCALES, 20).addComponent(GOLDEN_RIVER_BASS).setRecipeTime(60).setRecipeYield(3));
STONE_BODY.addRecipe(new Recipe(Workstations.GRINDER).addComponent(CLAY, 12).addComponent(STONE_BRICK, 4).setRecipeTime(60));
STONE_BRICK.addRecipe(new Recipe(Workstations.GRINDER).addComponent(STONE, 12).setRecipeTime(20));
STONE_DUST.addRecipe(new Recipe(Workstations.GRINDER).addComponent(STONE, 12).setRecipeTime(20));
SULPHUR.addRecipe(new Recipe(Workstations.FURNACE).addComponent(SULPHUR_ORE, 20).setRecipeTime(90));
THE_EMBER_CHAIN.addRecipe(new Recipe(Workstations.JEWELCRAFTING_TABLE).addComponent(GREATER_BLOOD_ESSENCE).addComponent(CRUDE_EMERALD, 4).addComponent(GRAVE_DUST, 8).setRecipeTime(30));
THE_FROZEN_EYE.addRecipe(new Recipe(Workstations.JEWELCRAFTING_TABLE).addComponent(GREATER_BLOOD_ESSENCE).addComponent(CRUDE_SAPPHIRE, 4).addComponent(GRAVE_DUST, 8).setRecipeTime(30));
TOPAZ_AMULET.addRecipe(new Recipe(Workstations.JEWELCRAFTING_TABLE).addComponent(REGULAR_TOPAZ, 4).addComponent(SCOURGESTONE, 8).addComponent(SCOURGE_PENDANT).setRecipeTime(5));
TRAVELERS_WRAP.addRecipe(new Recipe(Workstations.TAILORING_BENCH).addComponent(CLOTH, 4).addComponent(LEATHER, 4).setRecipeTime(10));
VERMIN_SALVE.addRecipe(new Recipe(Workstations.ALCHEMY_TABLE).addComponent(RAT).addComponent(PLANT_FIBER, 60).addComponent(BONE, 20).setRecipeTime(10));
WATER_FILLED_BOTTLE.addRecipe(new Recipe(Workstations.ENVIRONMENT).addComponent(EMPTY_GLASS_BOTTLE));
WATER_FILLED_CANTEEN.addRecipe(new Recipe(Workstations.ENVIRONMENT).addComponent(EMPTY_CANTEEN));
WHETSTONE.addRecipe(new Recipe(Workstations.FURNACE).addComponent(COPPER_INGOT).addComponent(STONE_DUST, 12).setRecipeTime(60));
WITCH_POTION.addRecipe(new Recipe(Workstations.ALCHEMY_TABLE).addComponent(SWAMP_DWELLER).addComponent(SNOW_FLOWER, 90).addComponent(WATER_FILLED_BOTTLE).setRecipeTime(30));
WOOL_THREAD.addRecipe(new Recipe(Workstations.LOOM).addComponent(FIRE_BLOSSOM, 12).addComponent(COARSE_THREAD, 8).setRecipeTime(60));
WRANGLERS_POTION.addRecipe(new Recipe(Workstations.ALCHEMY_TABLE).addComponent(FIRE_BLOSSOM, 60).addComponent(WATER_FILLED_BOTTLE).setRecipeTime(30));